#  version: 1.0.0

# title: Petr Vavilov
# name: Petr Vavilov
# tagline:
# description: Мой блог

# author:
#   name: Petr Vavilov
#   url: https://github.com/petrvav
#   email:

# url: http://petrvav.github.io
# github_username: PetrVav
# permalink: /:year/:title
# baseurl: '/blog'
# paginate: 5

# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-paginate

# lsi: false
# safe: true
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false 



# # Site settings
title: Home
email: petr.v.2019@mail.ru
description: Мой блог
baseurl: /blog
url: "http://petrvav.github.io" 
# github_username: PetrVav

# Build settings
markdown: kramdown